[tool.poetry]
name = "clp-mcp-server"
version = "0.5.1-dev"
description = "MCP server for CLP"
authors = ["YScope Inc. <dev@yscope.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
httpx = ">=0.28.1"
click = ">=8.2.1"
fastmcp = ">=2.10.0,<2.11.0"
smart-open = ">=1.8.2"
uvicorn = ">=0.27.0"

[tool.poetry.scripts]
clp-mcp-server = "clp_mcp_server:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.uv]
lockfile = "uv.lock"